#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# testService:
#     path: /testSrvProy
#     controller: App\Controller\testControllerSPT::respTestSrvTorneos

testService:
    # Matches /blog exactly
    path: /api/users
    controller: App\Controller\testControllerSPT::respTestSrvTorneos

# ###############################################################
# ########################### deportes ##########################

serviceSport:
    path: /api/sports
    controller: App\Controller\DeporteController::allSports

# ###############################################################
# ########################### usuarios ##########################
serviceUser:
    path: /api/all-users
    controller: App\Controller\UsuarioController::getUsers
srvCrearUsuario:
    path: /api/users
    controller: App\Controller\UsuarioController::create

# ###############################################################
# ########################### competencias ######################
serviceCompetition:
    path: /api/existcompetition
    controller: App\Controller\CompetenciaController::existCompetition

# ###############################################################
# ################# tipos de organizaciones ######################
serviceTypeOrg:
    path: /api/typesorg
    controller: App\Controller\TipoOrganizacionController::typesOrg