#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# ###############################################################
# ########################### deportes ##########################

serviceSport:
    path: /api/sports
    controller: App\Controller\DeporteController::allSports

# ###############################################################
# ########################### usuarios ##########################
serviceUser:
    path: /api/users
    controller: App\Controller\UsuarioController::getUsers
srvCrearUsuario:
    path: /api/user
    controller: App\Controller\UsuarioController::create

# ###############################################################
# ########################### competencias ######################
serviceCompetition:
    path: /api/existcompetition
    controller: App\Controller\CompetenciaController::existCompetition

# ###############################################################
# ################# tipos de organizaciones ######################
serviceTypeOrg:
    path: /api/typesorg
    controller: App\Controller\TipoOrganizacionController::typesOrg